spring.application.name=demo
spring.ai.google.genai.model=gemini-1.5-flash
logging.level.org.springframework.security=DEBUG
# data configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#auto create / update schema
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true

#jwt config (Ms)
hg.app.jwtSecret=${JWT_SECRET}
hg.app.jwtExpirationSecond=604800
hg.app.jwtRefreshable-duration=600

#Thread config
spring.threads.virtual.enabled=true